services:
  app_proxy:
    environment:
      APP_HOST: mrv777-omb-public-pool_proxy_1
      APP_PORT: 80
      PROXY_AUTH_WHITELIST: "/api/*"

  web:
    image: mrv777/omb-public-pool-ui:0.0.13@sha256:1a076f4981adc283d2eb8b6f1c3f90d9bd4a00a366d887b62c05f442ee0f9e17
    restart: on-failure
    stop_grace_period: 30s
    environment:
      - DOMAIN=$DEVICE_DOMAIN_NAME

  server:
    image: mrv777/omb-public-pool:0.0.4@sha256:1b4d6e9170c0b8d68a3f86261d0a4b55a29c1d0469a0d4d2f4228e5e24e7c9c0
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "2018:2018/tcp"
    volumes:
      - "${APP_DATA_DIR}/data/database:/public-pool/DB"
    environment:
      - NODE_ENV=production
      - BITCOIN_RPC_URL=http://${APP_BITCOIN_NODE_IP}
      - BITCOIN_RPC_USER=${APP_BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${APP_BITCOIN_RPC_PASS}
      - BITCOIN_RPC_PORT=${APP_BITCOIN_RPC_PORT}
      - BITCOIN_RPC_TIMEOUT=10000
      - API_PORT=2019
      - STRATUM_PORT=2018
      - NETWORK=mainnet
      - API_SECURE=false
      - ENABLE_SOLO=true
      - ENABLE_PROXY=false

  proxy:
    image: nginx:1.25.3@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
    volumes:
      - ${APP_DATA_DIR}/data/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - server
    restart: on-failure
    ports:
      - "2019:80"
