services:
  app_proxy:
    environment:
      APP_HOST: mrv777-omb-public-pool_proxy_1
      APP_PORT: 80
      PROXY_AUTH_WHITELIST: "/api/*"

  web:
    image: mrv777/omb-public-pool-ui:0.0.15@sha256:1c7bbba40d5d3107429434ba4b0ad18021a008344c4b97cd6013994e59a553ae
    restart: on-failure
    stop_grace_period: 30s
    environment:
      - DOMAIN=$DEVICE_DOMAIN_NAME

  server:
    image: mrv777/omb-public-pool:0.0.6@sha256:740f287b78cbf8620e06f89dbdd857e2dbb65cac1c857ac889ff4c51acb6fc0b
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "2018:2018/tcp"
    volumes:
      - "${APP_DATA_DIR}/data/database:/public-pool/DB"
    environment:
      - NODE_ENV=production
      - BITCOIN_RPC_URL=http://${APP_BITCOIN_NODE_IP}
      - BITCOIN_RPC_USER=${APP_BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${APP_BITCOIN_RPC_PASS}
      - BITCOIN_RPC_PORT=${APP_BITCOIN_RPC_PORT}
      - BITCOIN_RPC_TIMEOUT=10000
      - API_PORT=2019
      - STRATUM_PORT=2018
      - NETWORK=mainnet
      - API_SECURE=false
      - ENABLE_SOLO=true
      - ENABLE_PROXY=false

  proxy:
    image: nginx:1.25.3@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
    volumes:
      - ${APP_DATA_DIR}/data/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - server
    restart: on-failure
    ports:
      - "2019:80"
