version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mrv777-ordinals_ord_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  ord:
    image: mrv777/ordinals:0.18.0@sha256:6595bd5fae7a172dae1e37ed667decbf0a06e2799bb730bcfcd950d064b625a9
    # This needs to run as root
    # user: "1000:1000"
    restart: on-failure
    # First-inscription-height may not be needed in the future
    command: "ord --index-runes --config /var/lib/ord/ord.yaml server --http"
    volumes:
      - ${APP_DATA_DIR}/data/ord:/var/lib/ord
      - ${APP_BITCOIN_DATA_DIR}:/var/lib/bitcoind:ro
