#!/usr/bin/env bash
set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../data)"
ORDINALS_DATA_DIR="${APP_DATA_DIR}/ord"
DESIRED_OWNER="1000:1000"

if [ ! -f "${ORDINALS_DATA_DIR}/ord.yaml" ]; then
    # Define the content for ord.yaml
    cat <<EOF >"${ORDINALS_DATA_DIR}/ord.yaml"
cookie_file: /var/lib/bitcoind/.cookie 
data_dir: /var/lib/ord
bitcoin_data_dir: /var/lib/bitcoind
bitcoin_rpc_url: ${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT}
chain: ${APP_BITCOIN_NETWORK}
EOF

    echo "ord.yaml file has been created in ${ORDINALS_DATA_DIR}/ directory."
else
    echo "ord.yaml already exists in ${ORDINALS_DATA_DIR}/ directory. Exiting..."
    exit 1
fi

# set_correct_permissions() {
# 	local -r path="${1}"

# 	if [[ -d "${path}" ]]; then
# 		owner=$(stat -c "%u:%g" "${path}")

# 		if [[ "${owner}" != "${DESIRED_OWNER}" ]]; then
# 			chown -R "${DESIRED_OWNER}" "${path}"
# 		fi
# 	fi
# }

# if [[ -f "${APP_DATA_DIR}/index.redb" ]]; then
#   rm -f "${APP_DATA_DIR}/index.redb"
#   mkdir -p "${ORDINALS_DATA_DIR}"
#   # set correct permissions for both data and ord
#   set_correct_permissions "${APP_DATA_DIR}"
# fi
